---
- hosts: managers
  tasks:
    - name: Copy vote.yml
      template:
        src: ./files/vote.yml
        dest: vote.yml

    - name:  Create directory for postgresql database
      become: true
      file:
        path: /data/postgresql/data
        state: directory
        mode: 0777
    - name:  Deploy demo service
      docker_stack:
        compose:
          - ./vote.yml
        state: present
        name:  vote

