---
- hosts: all
  become: true
  vars_files: 
    - vars.yml

  tasks:
    - name: Add user "{{docker_user}}"
      user:
        name: "{{docker_user}}"
        comment: "{{docker_user_full}}"
        groups: sudo 
        shell: /bin/bash
        password: "$6$mysecretsalt$8.AvNg6M47drSMjGVohsvDlGep/7gqSY584PRfKp0udnW9eFsT1tIQL6TaNnmyi9qJTCIiNIirqHSjiCCUkmv/"
        update_password: on_create
        state: present
      register: user_ret
    

    - name: Set authorized key taken from file
      authorized_key:
        user: "{{docker_user}}"
        state: present
        key: "{{ lookup('file', '/home/ottar/.ssh/id_rsa.pub') }}"

    - name: Copy sudo file
      template: 
        src: ./files/010_nopass
        dest: "/etc/sudoers.d/010_{{docker_user}}_nopass"
        owner: root
        group: root
        mode: 0644

    - name:  Edit hosts file
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.33.30 master
          192.168.33.31 node1
          192.168.33.32 node2
    
