---
- hosts: all
  become: true
  vars_files: 
    - vars.yml

  tasks:
    - name: Add user "{{docker_user}}"
      user:
        name: "{{docker_user}}"
        groups: sudo 
        shell: /bin/bash
        password: "!"
        update_password: on_create
        state: present
      register: user_ret
    

    - name: Set authorized key taken from file
      authorized_key:
        user: "{{docker_user}}"
        state: present
        key: "{{pub_key}}"

    - name: Copy sudo file
      template: 
        src: ./files/010_nopass
        dest: "/etc/sudoers.d/010_{{docker_user}}_nopass"
        owner: root
        group: root
        mode: 0644

    - name:  Edit hosts file
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.33.30 vamaster
          192.168.33.31 vanode1
          192.168.33.32 vanode2
    
